/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts/index.js';
export type { contracts };
import type * as upgradeability from './upgradeability/index.js';
export type { upgradeability };