/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface ValidationLogicInterface extends Interface {
    getFunction(nameOrSignature: "REBALANCE_UP_LIQUIDITY_RATE_THRESHOLD" | "REBALANCE_UP_USAGE_RATIO_THRESHOLD"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'REBALANCE_UP_LIQUIDITY_RATE_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'REBALANCE_UP_USAGE_RATIO_THRESHOLD', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'REBALANCE_UP_LIQUIDITY_RATE_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REBALANCE_UP_USAGE_RATIO_THRESHOLD', data: BytesLike): Result;
  }

  

  export interface ValidationLogic extends BaseContract {
    
    connect(runner?: ContractRunner | null): ValidationLogic;
    waitForDeployment(): Promise<this>;

    interface: ValidationLogicInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    REBALANCE_UP_LIQUIDITY_RATE_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    REBALANCE_UP_USAGE_RATIO_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'REBALANCE_UP_LIQUIDITY_RATE_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'REBALANCE_UP_USAGE_RATIO_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }