/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPriceOracleGetter, IPriceOracleGetterInterface } from "../../interfaces/IPriceOracleGetter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "getAssetPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPriceOracleGetter__factory {
    static readonly abi = _abi;
    static createInterface(): IPriceOracleGetterInterface {
      return new Interface(_abi) as IPriceOracleGetterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPriceOracleGetter {
      return new Contract(address, _abi, runner) as unknown as IPriceOracleGetter;
    }
  }
  