/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace DataTypes {
      
    export type LoanDataStruct = {borrower: AddressLike, depositAmount: BigNumberish, loanAmount: BigNumberish, collateralAmount: BigNumberish, estimatedMonthlyPayment: BigNumberish, duration: BigNumberish, createdAt: BigNumberish, insuranceID: BigNumberish, lastPaymentTimestamp: BigNumberish, status: BigNumberish}

    export type LoanDataStructOutput = [borrower: string, depositAmount: bigint, loanAmount: bigint, collateralAmount: bigint, estimatedMonthlyPayment: bigint, duration: bigint, createdAt: bigint, insuranceID: bigint, lastPaymentTimestamp: bigint, status: bigint] & {borrower: string, depositAmount: bigint, loanAmount: bigint, collateralAmount: bigint, estimatedMonthlyPayment: bigint, duration: bigint, createdAt: bigint, insuranceID: bigint, lastPaymentTimestamp: bigint, status: bigint }
  
    }

  export interface MockLoanInterface extends Interface {
    getFunction(nameOrSignature: "calculateStrikePrice" | "closeLoan" | "createActiveLoan" | "fullLiquidationCount" | "getCollateralAsset" | "getDebtAsset" | "getGracePeriod" | "getLiquidationBuffer" | "getLoanByLSA" | "getLoanDetails" | "getPreClosureFee" | "getPremiumCollector" | "getRepaymentInterval" | "getUserAllLoans" | "getUserLoanAtIndex" | "getUserLoanCount" | "initializeLoan" | "loanExists" | "makeLoanOverdue" | "microLiquidationCount" | "repay" | "setCollateralAmount" | "setCollateralAssetAddress" | "setDebtAssetAddress" | "setDuration" | "setEstimatedMonthlyPayment" | "setGracePeriod" | "setGracePeriodValue" | "setInsuranceId" | "setLastPaymentTimestamp" | "setLiquidationBuffer" | "setLoanData" | "setLoanStatus" | "setLoanVaultFactory" | "setPreClosureFee" | "setPremiumCollector" | "setSwapAdapter" | "setZQuoter" | "updateInsuranceId" | "updateLoanDataForFullLiquidation" | "updateLoanDataForMicroLiquidation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Loan__ClosedLoan" | "Loan__EscrowUpdated" | "Loan__GracePeriodUpdated" | "Loan__InsuranceIDUpdated" | "Loan__LiquidationBufferUpdated" | "Loan__LoanCreated" | "Loan__LoanDataFullLiquidationUpdated" | "Loan__LoanDataMicroLiquidationUpdated" | "Loan__LoanRepaid" | "Loan__LoanStatusUpdated" | "Loan__LoanVaultFactoryUpdated" | "Loan__MaxLoanAmountUpdated" | "Loan__PreClosureFeeUpdated" | "Loan__PremiumCollectorUpdated" | "Loan__SwapAdapterUpdated" | "Loan__ZQuoterUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'calculateStrikePrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeLoan', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'createActiveLoan', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fullLiquidationCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCollateralAsset', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDebtAsset', values?: undefined): string;
encodeFunctionData(functionFragment: 'getGracePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLiquidationBuffer', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLoanByLSA', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getLoanDetails', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPreClosureFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPremiumCollector', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRepaymentInterval', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserAllLoans', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserLoanAtIndex', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserLoanCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initializeLoan', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'loanExists', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'makeLoanOverdue', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'microLiquidationCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'repay', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setCollateralAmount', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setCollateralAssetAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setDebtAssetAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setDuration', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setEstimatedMonthlyPayment', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setGracePeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setGracePeriodValue', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setInsuranceId', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setLastPaymentTimestamp', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setLiquidationBuffer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setLoanData', values: [AddressLike, DataTypes.LoanDataStruct]): string;
encodeFunctionData(functionFragment: 'setLoanStatus', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setLoanVaultFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPreClosureFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPremiumCollector', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setSwapAdapter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setZQuoter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateInsuranceId', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateLoanDataForFullLiquidation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateLoanDataForMicroLiquidation', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'calculateStrikePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createActiveLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fullLiquidationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCollateralAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDebtAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGracePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLiquidationBuffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLoanByLSA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLoanDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPreClosureFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPremiumCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRepaymentInterval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserAllLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserLoanAtIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserLoanCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'loanExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'makeLoanOverdue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'microLiquidationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCollateralAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCollateralAssetAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDebtAssetAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEstimatedMonthlyPayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGracePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGracePeriodValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setInsuranceId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLastPaymentTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLiquidationBuffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLoanData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLoanStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLoanVaultFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPreClosureFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPremiumCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSwapAdapter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setZQuoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateInsuranceId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateLoanDataForFullLiquidation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateLoanDataForMicroLiquidation', data: BytesLike): Result;
  }

  
    export namespace Loan__ClosedLoanEvent {
      export type InputTuple = [lsa: AddressLike];
      export type OutputTuple = [lsa: string];
      export interface OutputObject {lsa: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__EscrowUpdatedEvent {
      export type InputTuple = [newEscrow: AddressLike];
      export type OutputTuple = [newEscrow: string];
      export interface OutputObject {newEscrow: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__GracePeriodUpdatedEvent {
      export type InputTuple = [newGracePeriod: BigNumberish];
      export type OutputTuple = [newGracePeriod: bigint];
      export interface OutputObject {newGracePeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__InsuranceIDUpdatedEvent {
      export type InputTuple = [lsa: AddressLike, insuranceID: BigNumberish];
      export type OutputTuple = [lsa: string, insuranceID: bigint];
      export interface OutputObject {lsa: string, insuranceID: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__LiquidationBufferUpdatedEvent {
      export type InputTuple = [newBuffer: BigNumberish];
      export type OutputTuple = [newBuffer: bigint];
      export interface OutputObject {newBuffer: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__LoanCreatedEvent {
      export type InputTuple = [borrower: AddressLike, lsa: AddressLike, loanAmount: BigNumberish, collateralAmount: BigNumberish, data: BytesLike];
      export type OutputTuple = [borrower: string, lsa: string, loanAmount: bigint, collateralAmount: bigint, data: string];
      export interface OutputObject {borrower: string, lsa: string, loanAmount: bigint, collateralAmount: bigint, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__LoanDataFullLiquidationUpdatedEvent {
      export type InputTuple = [lsa: AddressLike];
      export type OutputTuple = [lsa: string];
      export interface OutputObject {lsa: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__LoanDataMicroLiquidationUpdatedEvent {
      export type InputTuple = [lsa: AddressLike, newDuration: BigNumberish];
      export type OutputTuple = [lsa: string, newDuration: bigint];
      export interface OutputObject {lsa: string, newDuration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__LoanRepaidEvent {
      export type InputTuple = [lsa: AddressLike, amountRepaid: BigNumberish];
      export type OutputTuple = [lsa: string, amountRepaid: bigint];
      export interface OutputObject {lsa: string, amountRepaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__LoanStatusUpdatedEvent {
      export type InputTuple = [lsa: AddressLike, oldStatus: BigNumberish, newStatus: BigNumberish];
      export type OutputTuple = [lsa: string, oldStatus: bigint, newStatus: bigint];
      export interface OutputObject {lsa: string, oldStatus: bigint, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__LoanVaultFactoryUpdatedEvent {
      export type InputTuple = [newFactory: AddressLike];
      export type OutputTuple = [newFactory: string];
      export interface OutputObject {newFactory: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__MaxLoanAmountUpdatedEvent {
      export type InputTuple = [newAmount: BigNumberish];
      export type OutputTuple = [newAmount: bigint];
      export interface OutputObject {newAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__PreClosureFeeUpdatedEvent {
      export type InputTuple = [newPreClosureFee: BigNumberish];
      export type OutputTuple = [newPreClosureFee: bigint];
      export interface OutputObject {newPreClosureFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__PremiumCollectorUpdatedEvent {
      export type InputTuple = [newPremiumCollector: AddressLike];
      export type OutputTuple = [newPremiumCollector: string];
      export interface OutputObject {newPremiumCollector: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__SwapAdapterUpdatedEvent {
      export type InputTuple = [newSwapAdapter: AddressLike];
      export type OutputTuple = [newSwapAdapter: string];
      export interface OutputObject {newSwapAdapter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace Loan__ZQuoterUpdatedEvent {
      export type InputTuple = [newZQuoter: AddressLike];
      export type OutputTuple = [newZQuoter: string];
      export interface OutputObject {newZQuoter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockLoan extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockLoan;
    waitForDeployment(): Promise<this>;

    interface: MockLoanInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateStrikePrice: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    closeLoan: TypedContractMethod<
      [arg0: AddressLike, arg1: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    createActiveLoan: TypedContractMethod<
      [lsa: AddressLike, borrower: AddressLike, collateralAmount: BigNumberish, loanAmount: BigNumberish, duration: BigNumberish, monthlyPayment: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fullLiquidationCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getCollateralAsset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getDebtAsset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getGracePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getLiquidationBuffer: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getLoanByLSA: TypedContractMethod<
      [lsa: AddressLike, ],
      [DataTypes.LoanDataStructOutput],
      'view'
    >
    

    
    getLoanDetails: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, bigint, bigint]],
      'view'
    >
    

    
    getPreClosureFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPremiumCollector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRepaymentInterval: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getUserAllLoans: TypedContractMethod<
      [arg0: AddressLike, ],
      [DataTypes.LoanDataStructOutput[]],
      'view'
    >
    

    
    getUserLoanAtIndex: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getUserLoanCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    initializeLoan: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    loanExists: TypedContractMethod<
      [lsa: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    makeLoanOverdue: TypedContractMethod<
      [lsa: AddressLike, daysOverdue: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    microLiquidationCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    repay: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    setCollateralAmount: TypedContractMethod<
      [lsa: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setCollateralAssetAddress: TypedContractMethod<
      [collateralAsset_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDebtAssetAddress: TypedContractMethod<
      [debtAsset_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDuration: TypedContractMethod<
      [lsa: AddressLike, duration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setEstimatedMonthlyPayment: TypedContractMethod<
      [lsa: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setGracePeriod: TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setGracePeriodValue: TypedContractMethod<
      [gracePeriod_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setInsuranceId: TypedContractMethod<
      [lsa: AddressLike, insuranceId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setLastPaymentTimestamp: TypedContractMethod<
      [lsa: AddressLike, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setLiquidationBuffer: TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setLoanData: TypedContractMethod<
      [lsa: AddressLike, data: DataTypes.LoanDataStruct, ],
      [void],
      'nonpayable'
    >
    

    
    setLoanStatus: TypedContractMethod<
      [lsa: AddressLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setLoanVaultFactory: TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPreClosureFee: TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPremiumCollector: TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setSwapAdapter: TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setZQuoter: TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateInsuranceId: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateLoanDataForFullLiquidation: TypedContractMethod<
      [lsa: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateLoanDataForMicroLiquidation: TypedContractMethod<
      [lsa: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateStrikePrice'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'closeLoan'): TypedContractMethod<
      [arg0: AddressLike, arg1: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createActiveLoan'): TypedContractMethod<
      [lsa: AddressLike, borrower: AddressLike, collateralAmount: BigNumberish, loanAmount: BigNumberish, duration: BigNumberish, monthlyPayment: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fullLiquidationCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCollateralAsset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDebtAsset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getGracePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLiquidationBuffer'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLoanByLSA'): TypedContractMethod<
      [lsa: AddressLike, ],
      [DataTypes.LoanDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getLoanDetails'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getPreClosureFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPremiumCollector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRepaymentInterval'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserAllLoans'): TypedContractMethod<
      [arg0: AddressLike, ],
      [DataTypes.LoanDataStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUserLoanAtIndex'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUserLoanCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initializeLoan'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'loanExists'): TypedContractMethod<
      [lsa: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'makeLoanOverdue'): TypedContractMethod<
      [lsa: AddressLike, daysOverdue: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'microLiquidationCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'repay'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCollateralAmount'): TypedContractMethod<
      [lsa: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCollateralAssetAddress'): TypedContractMethod<
      [collateralAsset_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDebtAssetAddress'): TypedContractMethod<
      [debtAsset_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDuration'): TypedContractMethod<
      [lsa: AddressLike, duration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEstimatedMonthlyPayment'): TypedContractMethod<
      [lsa: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGracePeriod'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGracePeriodValue'): TypedContractMethod<
      [gracePeriod_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setInsuranceId'): TypedContractMethod<
      [lsa: AddressLike, insuranceId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLastPaymentTimestamp'): TypedContractMethod<
      [lsa: AddressLike, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLiquidationBuffer'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLoanData'): TypedContractMethod<
      [lsa: AddressLike, data: DataTypes.LoanDataStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLoanStatus'): TypedContractMethod<
      [lsa: AddressLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLoanVaultFactory'): TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPreClosureFee'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPremiumCollector'): TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSwapAdapter'): TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setZQuoter'): TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateInsuranceId'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateLoanDataForFullLiquidation'): TypedContractMethod<
      [lsa: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateLoanDataForMicroLiquidation'): TypedContractMethod<
      [lsa: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Loan__ClosedLoan'): TypedContractEvent<Loan__ClosedLoanEvent.InputTuple, Loan__ClosedLoanEvent.OutputTuple, Loan__ClosedLoanEvent.OutputObject>;
getEvent(key: 'Loan__EscrowUpdated'): TypedContractEvent<Loan__EscrowUpdatedEvent.InputTuple, Loan__EscrowUpdatedEvent.OutputTuple, Loan__EscrowUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__GracePeriodUpdated'): TypedContractEvent<Loan__GracePeriodUpdatedEvent.InputTuple, Loan__GracePeriodUpdatedEvent.OutputTuple, Loan__GracePeriodUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__InsuranceIDUpdated'): TypedContractEvent<Loan__InsuranceIDUpdatedEvent.InputTuple, Loan__InsuranceIDUpdatedEvent.OutputTuple, Loan__InsuranceIDUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__LiquidationBufferUpdated'): TypedContractEvent<Loan__LiquidationBufferUpdatedEvent.InputTuple, Loan__LiquidationBufferUpdatedEvent.OutputTuple, Loan__LiquidationBufferUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__LoanCreated'): TypedContractEvent<Loan__LoanCreatedEvent.InputTuple, Loan__LoanCreatedEvent.OutputTuple, Loan__LoanCreatedEvent.OutputObject>;
getEvent(key: 'Loan__LoanDataFullLiquidationUpdated'): TypedContractEvent<Loan__LoanDataFullLiquidationUpdatedEvent.InputTuple, Loan__LoanDataFullLiquidationUpdatedEvent.OutputTuple, Loan__LoanDataFullLiquidationUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__LoanDataMicroLiquidationUpdated'): TypedContractEvent<Loan__LoanDataMicroLiquidationUpdatedEvent.InputTuple, Loan__LoanDataMicroLiquidationUpdatedEvent.OutputTuple, Loan__LoanDataMicroLiquidationUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__LoanRepaid'): TypedContractEvent<Loan__LoanRepaidEvent.InputTuple, Loan__LoanRepaidEvent.OutputTuple, Loan__LoanRepaidEvent.OutputObject>;
getEvent(key: 'Loan__LoanStatusUpdated'): TypedContractEvent<Loan__LoanStatusUpdatedEvent.InputTuple, Loan__LoanStatusUpdatedEvent.OutputTuple, Loan__LoanStatusUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__LoanVaultFactoryUpdated'): TypedContractEvent<Loan__LoanVaultFactoryUpdatedEvent.InputTuple, Loan__LoanVaultFactoryUpdatedEvent.OutputTuple, Loan__LoanVaultFactoryUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__MaxLoanAmountUpdated'): TypedContractEvent<Loan__MaxLoanAmountUpdatedEvent.InputTuple, Loan__MaxLoanAmountUpdatedEvent.OutputTuple, Loan__MaxLoanAmountUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__PreClosureFeeUpdated'): TypedContractEvent<Loan__PreClosureFeeUpdatedEvent.InputTuple, Loan__PreClosureFeeUpdatedEvent.OutputTuple, Loan__PreClosureFeeUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__PremiumCollectorUpdated'): TypedContractEvent<Loan__PremiumCollectorUpdatedEvent.InputTuple, Loan__PremiumCollectorUpdatedEvent.OutputTuple, Loan__PremiumCollectorUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__SwapAdapterUpdated'): TypedContractEvent<Loan__SwapAdapterUpdatedEvent.InputTuple, Loan__SwapAdapterUpdatedEvent.OutputTuple, Loan__SwapAdapterUpdatedEvent.OutputObject>;
getEvent(key: 'Loan__ZQuoterUpdated'): TypedContractEvent<Loan__ZQuoterUpdatedEvent.InputTuple, Loan__ZQuoterUpdatedEvent.OutputTuple, Loan__ZQuoterUpdatedEvent.OutputObject>;

    filters: {
      
      'Loan__ClosedLoan(address)': TypedContractEvent<Loan__ClosedLoanEvent.InputTuple, Loan__ClosedLoanEvent.OutputTuple, Loan__ClosedLoanEvent.OutputObject>;
      Loan__ClosedLoan: TypedContractEvent<Loan__ClosedLoanEvent.InputTuple, Loan__ClosedLoanEvent.OutputTuple, Loan__ClosedLoanEvent.OutputObject>;
    

      'Loan__EscrowUpdated(address)': TypedContractEvent<Loan__EscrowUpdatedEvent.InputTuple, Loan__EscrowUpdatedEvent.OutputTuple, Loan__EscrowUpdatedEvent.OutputObject>;
      Loan__EscrowUpdated: TypedContractEvent<Loan__EscrowUpdatedEvent.InputTuple, Loan__EscrowUpdatedEvent.OutputTuple, Loan__EscrowUpdatedEvent.OutputObject>;
    

      'Loan__GracePeriodUpdated(uint256)': TypedContractEvent<Loan__GracePeriodUpdatedEvent.InputTuple, Loan__GracePeriodUpdatedEvent.OutputTuple, Loan__GracePeriodUpdatedEvent.OutputObject>;
      Loan__GracePeriodUpdated: TypedContractEvent<Loan__GracePeriodUpdatedEvent.InputTuple, Loan__GracePeriodUpdatedEvent.OutputTuple, Loan__GracePeriodUpdatedEvent.OutputObject>;
    

      'Loan__InsuranceIDUpdated(address,uint256)': TypedContractEvent<Loan__InsuranceIDUpdatedEvent.InputTuple, Loan__InsuranceIDUpdatedEvent.OutputTuple, Loan__InsuranceIDUpdatedEvent.OutputObject>;
      Loan__InsuranceIDUpdated: TypedContractEvent<Loan__InsuranceIDUpdatedEvent.InputTuple, Loan__InsuranceIDUpdatedEvent.OutputTuple, Loan__InsuranceIDUpdatedEvent.OutputObject>;
    

      'Loan__LiquidationBufferUpdated(uint256)': TypedContractEvent<Loan__LiquidationBufferUpdatedEvent.InputTuple, Loan__LiquidationBufferUpdatedEvent.OutputTuple, Loan__LiquidationBufferUpdatedEvent.OutputObject>;
      Loan__LiquidationBufferUpdated: TypedContractEvent<Loan__LiquidationBufferUpdatedEvent.InputTuple, Loan__LiquidationBufferUpdatedEvent.OutputTuple, Loan__LiquidationBufferUpdatedEvent.OutputObject>;
    

      'Loan__LoanCreated(address,address,uint256,uint256,bytes)': TypedContractEvent<Loan__LoanCreatedEvent.InputTuple, Loan__LoanCreatedEvent.OutputTuple, Loan__LoanCreatedEvent.OutputObject>;
      Loan__LoanCreated: TypedContractEvent<Loan__LoanCreatedEvent.InputTuple, Loan__LoanCreatedEvent.OutputTuple, Loan__LoanCreatedEvent.OutputObject>;
    

      'Loan__LoanDataFullLiquidationUpdated(address)': TypedContractEvent<Loan__LoanDataFullLiquidationUpdatedEvent.InputTuple, Loan__LoanDataFullLiquidationUpdatedEvent.OutputTuple, Loan__LoanDataFullLiquidationUpdatedEvent.OutputObject>;
      Loan__LoanDataFullLiquidationUpdated: TypedContractEvent<Loan__LoanDataFullLiquidationUpdatedEvent.InputTuple, Loan__LoanDataFullLiquidationUpdatedEvent.OutputTuple, Loan__LoanDataFullLiquidationUpdatedEvent.OutputObject>;
    

      'Loan__LoanDataMicroLiquidationUpdated(address,uint256)': TypedContractEvent<Loan__LoanDataMicroLiquidationUpdatedEvent.InputTuple, Loan__LoanDataMicroLiquidationUpdatedEvent.OutputTuple, Loan__LoanDataMicroLiquidationUpdatedEvent.OutputObject>;
      Loan__LoanDataMicroLiquidationUpdated: TypedContractEvent<Loan__LoanDataMicroLiquidationUpdatedEvent.InputTuple, Loan__LoanDataMicroLiquidationUpdatedEvent.OutputTuple, Loan__LoanDataMicroLiquidationUpdatedEvent.OutputObject>;
    

      'Loan__LoanRepaid(address,uint256)': TypedContractEvent<Loan__LoanRepaidEvent.InputTuple, Loan__LoanRepaidEvent.OutputTuple, Loan__LoanRepaidEvent.OutputObject>;
      Loan__LoanRepaid: TypedContractEvent<Loan__LoanRepaidEvent.InputTuple, Loan__LoanRepaidEvent.OutputTuple, Loan__LoanRepaidEvent.OutputObject>;
    

      'Loan__LoanStatusUpdated(address,uint8,uint8)': TypedContractEvent<Loan__LoanStatusUpdatedEvent.InputTuple, Loan__LoanStatusUpdatedEvent.OutputTuple, Loan__LoanStatusUpdatedEvent.OutputObject>;
      Loan__LoanStatusUpdated: TypedContractEvent<Loan__LoanStatusUpdatedEvent.InputTuple, Loan__LoanStatusUpdatedEvent.OutputTuple, Loan__LoanStatusUpdatedEvent.OutputObject>;
    

      'Loan__LoanVaultFactoryUpdated(address)': TypedContractEvent<Loan__LoanVaultFactoryUpdatedEvent.InputTuple, Loan__LoanVaultFactoryUpdatedEvent.OutputTuple, Loan__LoanVaultFactoryUpdatedEvent.OutputObject>;
      Loan__LoanVaultFactoryUpdated: TypedContractEvent<Loan__LoanVaultFactoryUpdatedEvent.InputTuple, Loan__LoanVaultFactoryUpdatedEvent.OutputTuple, Loan__LoanVaultFactoryUpdatedEvent.OutputObject>;
    

      'Loan__MaxLoanAmountUpdated(uint256)': TypedContractEvent<Loan__MaxLoanAmountUpdatedEvent.InputTuple, Loan__MaxLoanAmountUpdatedEvent.OutputTuple, Loan__MaxLoanAmountUpdatedEvent.OutputObject>;
      Loan__MaxLoanAmountUpdated: TypedContractEvent<Loan__MaxLoanAmountUpdatedEvent.InputTuple, Loan__MaxLoanAmountUpdatedEvent.OutputTuple, Loan__MaxLoanAmountUpdatedEvent.OutputObject>;
    

      'Loan__PreClosureFeeUpdated(uint256)': TypedContractEvent<Loan__PreClosureFeeUpdatedEvent.InputTuple, Loan__PreClosureFeeUpdatedEvent.OutputTuple, Loan__PreClosureFeeUpdatedEvent.OutputObject>;
      Loan__PreClosureFeeUpdated: TypedContractEvent<Loan__PreClosureFeeUpdatedEvent.InputTuple, Loan__PreClosureFeeUpdatedEvent.OutputTuple, Loan__PreClosureFeeUpdatedEvent.OutputObject>;
    

      'Loan__PremiumCollectorUpdated(address)': TypedContractEvent<Loan__PremiumCollectorUpdatedEvent.InputTuple, Loan__PremiumCollectorUpdatedEvent.OutputTuple, Loan__PremiumCollectorUpdatedEvent.OutputObject>;
      Loan__PremiumCollectorUpdated: TypedContractEvent<Loan__PremiumCollectorUpdatedEvent.InputTuple, Loan__PremiumCollectorUpdatedEvent.OutputTuple, Loan__PremiumCollectorUpdatedEvent.OutputObject>;
    

      'Loan__SwapAdapterUpdated(address)': TypedContractEvent<Loan__SwapAdapterUpdatedEvent.InputTuple, Loan__SwapAdapterUpdatedEvent.OutputTuple, Loan__SwapAdapterUpdatedEvent.OutputObject>;
      Loan__SwapAdapterUpdated: TypedContractEvent<Loan__SwapAdapterUpdatedEvent.InputTuple, Loan__SwapAdapterUpdatedEvent.OutputTuple, Loan__SwapAdapterUpdatedEvent.OutputObject>;
    

      'Loan__ZQuoterUpdated(address)': TypedContractEvent<Loan__ZQuoterUpdatedEvent.InputTuple, Loan__ZQuoterUpdatedEvent.OutputTuple, Loan__ZQuoterUpdatedEvent.OutputObject>;
      Loan__ZQuoterUpdated: TypedContractEvent<Loan__ZQuoterUpdatedEvent.InputTuple, Loan__ZQuoterUpdatedEvent.OutputTuple, Loan__ZQuoterUpdatedEvent.OutputObject>;
    
    };
  }