/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IUiPoolDataProviderV2 {
      
    export type AggregatedReserveDataStruct = {underlyingAsset: AddressLike, name: string, symbol: string, decimals: BigNumberish, baseLTVasCollateral: BigNumberish, reserveLiquidationThreshold: BigNumberish, reserveLiquidationBonus: BigNumberish, reserveFactor: BigNumberish, usageAsCollateralEnabled: boolean, borrowingEnabled: boolean, stableBorrowRateEnabled: boolean, isActive: boolean, isFrozen: boolean, liquidityIndex: BigNumberish, variableBorrowIndex: BigNumberish, liquidityRate: BigNumberish, variableBorrowRate: BigNumberish, stableBorrowRate: BigNumberish, lastUpdateTimestamp: BigNumberish, aTokenAddress: AddressLike, stableDebtTokenAddress: AddressLike, variableDebtTokenAddress: AddressLike, interestRateStrategyAddress: AddressLike, availableLiquidity: BigNumberish, totalPrincipalStableDebt: BigNumberish, averageStableRate: BigNumberish, stableDebtLastUpdateTimestamp: BigNumberish, totalScaledVariableDebt: BigNumberish, priceInMarketReferenceCurrency: BigNumberish, variableRateSlope1: BigNumberish, variableRateSlope2: BigNumberish, stableRateSlope1: BigNumberish, stableRateSlope2: BigNumberish}

    export type AggregatedReserveDataStructOutput = [underlyingAsset: string, name: string, symbol: string, decimals: bigint, baseLTVasCollateral: bigint, reserveLiquidationThreshold: bigint, reserveLiquidationBonus: bigint, reserveFactor: bigint, usageAsCollateralEnabled: boolean, borrowingEnabled: boolean, stableBorrowRateEnabled: boolean, isActive: boolean, isFrozen: boolean, liquidityIndex: bigint, variableBorrowIndex: bigint, liquidityRate: bigint, variableBorrowRate: bigint, stableBorrowRate: bigint, lastUpdateTimestamp: bigint, aTokenAddress: string, stableDebtTokenAddress: string, variableDebtTokenAddress: string, interestRateStrategyAddress: string, availableLiquidity: bigint, totalPrincipalStableDebt: bigint, averageStableRate: bigint, stableDebtLastUpdateTimestamp: bigint, totalScaledVariableDebt: bigint, priceInMarketReferenceCurrency: bigint, variableRateSlope1: bigint, variableRateSlope2: bigint, stableRateSlope1: bigint, stableRateSlope2: bigint] & {underlyingAsset: string, name: string, symbol: string, decimals: bigint, baseLTVasCollateral: bigint, reserveLiquidationThreshold: bigint, reserveLiquidationBonus: bigint, reserveFactor: bigint, usageAsCollateralEnabled: boolean, borrowingEnabled: boolean, stableBorrowRateEnabled: boolean, isActive: boolean, isFrozen: boolean, liquidityIndex: bigint, variableBorrowIndex: bigint, liquidityRate: bigint, variableBorrowRate: bigint, stableBorrowRate: bigint, lastUpdateTimestamp: bigint, aTokenAddress: string, stableDebtTokenAddress: string, variableDebtTokenAddress: string, interestRateStrategyAddress: string, availableLiquidity: bigint, totalPrincipalStableDebt: bigint, averageStableRate: bigint, stableDebtLastUpdateTimestamp: bigint, totalScaledVariableDebt: bigint, priceInMarketReferenceCurrency: bigint, variableRateSlope1: bigint, variableRateSlope2: bigint, stableRateSlope1: bigint, stableRateSlope2: bigint }
  

    export type BaseCurrencyInfoStruct = {marketReferenceCurrencyUnit: BigNumberish, marketReferenceCurrencyPriceInUsd: BigNumberish, networkBaseTokenPriceInUsd: BigNumberish, networkBaseTokenPriceDecimals: BigNumberish}

    export type BaseCurrencyInfoStructOutput = [marketReferenceCurrencyUnit: bigint, marketReferenceCurrencyPriceInUsd: bigint, networkBaseTokenPriceInUsd: bigint, networkBaseTokenPriceDecimals: bigint] & {marketReferenceCurrencyUnit: bigint, marketReferenceCurrencyPriceInUsd: bigint, networkBaseTokenPriceInUsd: bigint, networkBaseTokenPriceDecimals: bigint }
  

    export type UserReserveDataStruct = {underlyingAsset: AddressLike, scaledATokenBalance: BigNumberish, usageAsCollateralEnabledOnUser: boolean, stableBorrowRate: BigNumberish, scaledVariableDebt: BigNumberish, principalStableDebt: BigNumberish, stableBorrowLastUpdateTimestamp: BigNumberish}

    export type UserReserveDataStructOutput = [underlyingAsset: string, scaledATokenBalance: bigint, usageAsCollateralEnabledOnUser: boolean, stableBorrowRate: bigint, scaledVariableDebt: bigint, principalStableDebt: bigint, stableBorrowLastUpdateTimestamp: bigint] & {underlyingAsset: string, scaledATokenBalance: bigint, usageAsCollateralEnabledOnUser: boolean, stableBorrowRate: bigint, scaledVariableDebt: bigint, principalStableDebt: bigint, stableBorrowLastUpdateTimestamp: bigint }
  
    }

  export interface IUiPoolDataProviderV2Interface extends Interface {
    getFunction(nameOrSignature: "getReservesData" | "getReservesList" | "getUserReservesData"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getReservesData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReservesList', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserReservesData', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getReservesData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReservesList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserReservesData', data: BytesLike): Result;
  }

  

  export interface IUiPoolDataProviderV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): IUiPoolDataProviderV2;
    waitForDeployment(): Promise<this>;

    interface: IUiPoolDataProviderV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getReservesData: TypedContractMethod<
      [provider: AddressLike, ],
      [[IUiPoolDataProviderV2.AggregatedReserveDataStructOutput[], IUiPoolDataProviderV2.BaseCurrencyInfoStructOutput]],
      'view'
    >
    

    
    getReservesList: TypedContractMethod<
      [provider: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getUserReservesData: TypedContractMethod<
      [provider: AddressLike, user: AddressLike, ],
      [IUiPoolDataProviderV2.UserReserveDataStructOutput[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getReservesData'): TypedContractMethod<
      [provider: AddressLike, ],
      [[IUiPoolDataProviderV2.AggregatedReserveDataStructOutput[], IUiPoolDataProviderV2.BaseCurrencyInfoStructOutput]],
      'view'
    >;
getFunction(nameOrSignature: 'getReservesList'): TypedContractMethod<
      [provider: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUserReservesData'): TypedContractMethod<
      [provider: AddressLike, user: AddressLike, ],
      [IUiPoolDataProviderV2.UserReserveDataStructOutput[]],
      'view'
    >;

    

    filters: {
      
    };
  }