/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { PriceOracle, PriceOracleInterface } from "../../../mocks/oracle/PriceOracle.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "_asset",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "_price",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "AssetPriceUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "_price",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EthPriceUpdated",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_asset",
        "type": "address"
      }
    ],
    "name": "getAssetPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getEthUsdPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_asset",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_price",
        "type": "uint256"
      }
    ],
    "name": "setAssetPrice",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_price",
        "type": "uint256"
      }
    ],
    "name": "setEthUsdPrice",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561001057600080fd5b50610320806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806351323f7214610051578063a0a8045e1461007f578063b3596f0714610099578063b951883a146100bf575b600080fd5b61007d6004803603604081101561006757600080fd5b506001600160a01b0381351690602001356100dc565b005b610087610195565b60408051918252519081900360200190f35b610087600480360360208110156100af57600080fd5b50356001600160a01b03166101c7565b61007d600480360360208110156100d557600080fd5b503561020e565b6101057f8dca7855de456ab452ae29faa9c21f9dd19c23f9a29ae0cb2bdeba685e2f68d36102a2565b6001600160a01b03821660009081526020819052604090208190556101497fc825a409e18b4124843bab63765358ab5c8f6f4a73b8ab07c4205dcee6f9b8936102a2565b604080516001600160a01b038416815260208101839052428183015290517fce6e0b57367bae95ca7198e1172f653ea64a645c16ab586b4cefa9237bfc2d929181900360600190a15050565b60006101c07f755d24df032124f7f3bc70cedde2dc72f0dcb5928afee1e98adadf4e868e0d1f6102a2565b5060015490565b60006101f27f078542635a3d2a3581b50c28aa0758e5e35ee66737c8911d538dc0201d4b586f6102a2565b506001600160a01b031660009081526020819052604090205490565b6102377fef825f5763351ac0dcf2e7ae13b0725face7f28cbef19e17191d728728123b206102a2565b60018190556102657f7472db0de749db65c295b91eaac0ebdde233c76d1d034f0d41a00ee60f8d471f6102a2565b6040805182815242602082015281517fb4f35977939fa8b5ffe552d517a8ff5223046b1fdd3ee0068ae38d1e2b8d0016929181900390910190a150565b6102b9816102b16102bc6102e7565b63ffffffff16565b50565b60405181815273c0bec0bec0bec0bec0bec0bec0bec0bec0bec0be90600080602083855afa50505050565b9056fea2646970667358221220a3ce096827f08c8e336553bb25db754f061f731200220d945a8a53a73a9102e264736f6c634300060c0033";

  
      type PriceOracleConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: PriceOracleConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class PriceOracle__factory extends ContractFactory {
    
      constructor(...args: PriceOracleConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<PriceOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): PriceOracle__factory {
      return super.connect(runner) as PriceOracle__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): PriceOracleInterface {
      return new Interface(_abi) as PriceOracleInterface;
    }
    
    override attach(address: string | Addressable): PriceOracle {
      return super.attach(address) as PriceOracle;
    }
  static connect(address: string, runner?: ContractRunner | null): PriceOracle {
      return new Contract(address, _abi, runner) as unknown as PriceOracle;
    }
  }

  
  