/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockLoanProvider } from './MockLoanProvider.js';
export type { MockUSDCVault } from './MockUSDCVault.js';