/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LendingPoolAddressesProvider__factory } from './LendingPoolAddressesProvider__factory.js';
export { LendingPoolAddressesProviderRegistry__factory } from './LendingPoolAddressesProviderRegistry__factory.js';