/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Clones } from "./Clones";

export class ClonesFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Clones> {
    return super.deploy(overrides || {}) as Promise<Clones>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Clones {
    return super.attach(address) as Clones;
  }
  connect(signer: Signer): ClonesFactory {
    return super.connect(signer) as ClonesFactory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Clones {
    return new Contract(address, _abi, signerOrProvider) as Clones;
  }
}

const _abi = [
  {
    inputs: [],
    name: "CloneArgumentsTooLong",
    type: "error",
  },
];

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212209c06c0efb239fd36a3d9bb43277bc08cab481c374b8815bb273d099c8cf561fc64736f6c634300081e0033";
