/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IERC4626Interface extends ethers.utils.Interface {
  functions: {
    "asset()": FunctionFragment;
    "reallocateAssets(uint256)": FunctionFragment;
    "totalAssets()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reallocateAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reallocateAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;

  events: {};
}

export class IERC4626 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IERC4626Interface;

  functions: {
    asset(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "asset()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    reallocateAssets(
      amountToWithdraw: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "reallocateAssets(uint256)"(
      amountToWithdraw: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    totalAssets(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "totalAssets()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  asset(overrides?: CallOverrides): Promise<string>;

  "asset()"(overrides?: CallOverrides): Promise<string>;

  reallocateAssets(
    amountToWithdraw: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "reallocateAssets(uint256)"(
    amountToWithdraw: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  totalAssets(overrides?: CallOverrides): Promise<BigNumber>;

  "totalAssets()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    asset(overrides?: CallOverrides): Promise<string>;

    "asset()"(overrides?: CallOverrides): Promise<string>;

    reallocateAssets(
      amountToWithdraw: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "reallocateAssets(uint256)"(
      amountToWithdraw: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    totalAssets(overrides?: CallOverrides): Promise<BigNumber>;

    "totalAssets()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    asset(overrides?: CallOverrides): Promise<BigNumber>;

    "asset()"(overrides?: CallOverrides): Promise<BigNumber>;

    reallocateAssets(
      amountToWithdraw: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "reallocateAssets(uint256)"(
      amountToWithdraw: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    totalAssets(overrides?: CallOverrides): Promise<BigNumber>;

    "totalAssets()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    asset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "asset()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reallocateAssets(
      amountToWithdraw: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "reallocateAssets(uint256)"(
      amountToWithdraw: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    totalAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalAssets()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
