/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IEscrowInterface extends ethers.utils.Interface {
  functions: {
    "getLockedAmount(address)": FunctionFragment;
    "lockCollateral(address,uint256)": FunctionFragment;
    "unlockCollateral(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLockedAmount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCollateral",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCollateral",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLockedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCollateral",
    data: BytesLike
  ): Result;

  events: {};
}

export class IEscrow extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IEscrowInterface;

  functions: {
    getLockedAmount(
      lsa: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getLockedAmount(address)"(
      lsa: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    lockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "lockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    unlockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "unlockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getLockedAmount(lsa: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getLockedAmount(address)"(
    lsa: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lockCollateral(
    lsa: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "lockCollateral(address,uint256)"(
    lsa: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  unlockCollateral(
    lsa: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "unlockCollateral(address,uint256)"(
    lsa: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getLockedAmount(lsa: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getLockedAmount(address)"(
      lsa: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "lockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    unlockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "unlockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getLockedAmount(lsa: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getLockedAmount(address)"(
      lsa: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "lockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    unlockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "unlockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLockedAmount(
      lsa: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLockedAmount(address)"(
      lsa: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "lockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    unlockCollateral(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "unlockCollateral(address,uint256)"(
      lsa: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
