/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ILoanVaultFactoryInterface extends ethers.utils.Interface {
  functions: {
    "computeAddress(address,uint256)": FunctionFragment;
    "createLoanVault(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "computeAddress",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoanVault",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLoanVault",
    data: BytesLike
  ): Result;

  events: {
    "LoanVaultFactory__LoanContractUpdated(address,address)": EventFragment;
    "LoanVaultFactory__VaultCreated(address,address,bytes32)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "LoanVaultFactory__LoanContractUpdated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "LoanVaultFactory__VaultCreated"
  ): EventFragment;
}

export class ILoanVaultFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ILoanVaultFactoryInterface;

  functions: {
    computeAddress(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "computeAddress(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    createLoanVault(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createLoanVault(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  computeAddress(
    borrower: string,
    timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "computeAddress(address,uint256)"(
    borrower: string,
    timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  createLoanVault(
    borrower: string,
    timestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createLoanVault(address,uint256)"(
    borrower: string,
    timestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    computeAddress(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "computeAddress(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    createLoanVault(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "createLoanVault(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    LoanVaultFactory__LoanContractUpdated(
      oldContract: string | null,
      newContract: string | null
    ): EventFilter;

    LoanVaultFactory__VaultCreated(
      vault: string | null,
      borrower: string | null,
      salt: null
    ): EventFilter;
  };

  estimateGas: {
    computeAddress(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "computeAddress(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createLoanVault(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createLoanVault(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    computeAddress(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "computeAddress(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createLoanVault(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createLoanVault(address,uint256)"(
      borrower: string,
      timestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
