/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LoanStorageInterface extends ethers.utils.Interface {
  functions: {
    "LOAN_REPAYMENT_INTERVAL()": FunctionFragment;
    "MAX_COLLATERAL_AMOUNT()": FunctionFragment;
    "MAX_SLIPPAGE_BPS()": FunctionFragment;
    "i_AAVE_V3_POOL()": FunctionFragment;
    "i_BITMOR_POOL()": FunctionFragment;
    "i_ORACLE()": FunctionFragment;
    "s_loanVaultFactory()": FunctionFragment;
    "s_premiumCollector()": FunctionFragment;
    "s_swapAdapter()": FunctionFragment;
    "s_userLoanAtIndex(address,uint256)": FunctionFragment;
    "s_userLoanCount(address)": FunctionFragment;
    "s_zQuoter()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "LOAN_REPAYMENT_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COLLATERAL_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SLIPPAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_AAVE_V3_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_BITMOR_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_ORACLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_loanVaultFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_premiumCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_swapAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_userLoanAtIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_userLoanCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "s_zQuoter", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "LOAN_REPAYMENT_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COLLATERAL_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SLIPPAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_AAVE_V3_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_BITMOR_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_ORACLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_loanVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_premiumCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_swapAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_userLoanAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_userLoanCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_zQuoter", data: BytesLike): Result;

  events: {};
}

export class LoanStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LoanStorageInterface;

  functions: {
    LOAN_REPAYMENT_INTERVAL(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "LOAN_REPAYMENT_INTERVAL()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    MAX_COLLATERAL_AMOUNT(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "MAX_COLLATERAL_AMOUNT()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    MAX_SLIPPAGE_BPS(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "MAX_SLIPPAGE_BPS()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    i_AAVE_V3_POOL(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "i_AAVE_V3_POOL()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    i_BITMOR_POOL(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "i_BITMOR_POOL()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    i_ORACLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "i_ORACLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    s_loanVaultFactory(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "s_loanVaultFactory()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    s_premiumCollector(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "s_premiumCollector()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    s_swapAdapter(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "s_swapAdapter()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    s_userLoanAtIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "s_userLoanAtIndex(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    s_userLoanCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "s_userLoanCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    s_zQuoter(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "s_zQuoter()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  LOAN_REPAYMENT_INTERVAL(overrides?: CallOverrides): Promise<BigNumber>;

  "LOAN_REPAYMENT_INTERVAL()"(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_COLLATERAL_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_COLLATERAL_AMOUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_SLIPPAGE_BPS(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_SLIPPAGE_BPS()"(overrides?: CallOverrides): Promise<BigNumber>;

  i_AAVE_V3_POOL(overrides?: CallOverrides): Promise<string>;

  "i_AAVE_V3_POOL()"(overrides?: CallOverrides): Promise<string>;

  i_BITMOR_POOL(overrides?: CallOverrides): Promise<string>;

  "i_BITMOR_POOL()"(overrides?: CallOverrides): Promise<string>;

  i_ORACLE(overrides?: CallOverrides): Promise<string>;

  "i_ORACLE()"(overrides?: CallOverrides): Promise<string>;

  s_loanVaultFactory(overrides?: CallOverrides): Promise<string>;

  "s_loanVaultFactory()"(overrides?: CallOverrides): Promise<string>;

  s_premiumCollector(overrides?: CallOverrides): Promise<string>;

  "s_premiumCollector()"(overrides?: CallOverrides): Promise<string>;

  s_swapAdapter(overrides?: CallOverrides): Promise<string>;

  "s_swapAdapter()"(overrides?: CallOverrides): Promise<string>;

  s_userLoanAtIndex(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "s_userLoanAtIndex(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  s_userLoanCount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "s_userLoanCount(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  s_zQuoter(overrides?: CallOverrides): Promise<string>;

  "s_zQuoter()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    LOAN_REPAYMENT_INTERVAL(overrides?: CallOverrides): Promise<BigNumber>;

    "LOAN_REPAYMENT_INTERVAL()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_COLLATERAL_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_COLLATERAL_AMOUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_SLIPPAGE_BPS(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_SLIPPAGE_BPS()"(overrides?: CallOverrides): Promise<BigNumber>;

    i_AAVE_V3_POOL(overrides?: CallOverrides): Promise<string>;

    "i_AAVE_V3_POOL()"(overrides?: CallOverrides): Promise<string>;

    i_BITMOR_POOL(overrides?: CallOverrides): Promise<string>;

    "i_BITMOR_POOL()"(overrides?: CallOverrides): Promise<string>;

    i_ORACLE(overrides?: CallOverrides): Promise<string>;

    "i_ORACLE()"(overrides?: CallOverrides): Promise<string>;

    s_loanVaultFactory(overrides?: CallOverrides): Promise<string>;

    "s_loanVaultFactory()"(overrides?: CallOverrides): Promise<string>;

    s_premiumCollector(overrides?: CallOverrides): Promise<string>;

    "s_premiumCollector()"(overrides?: CallOverrides): Promise<string>;

    s_swapAdapter(overrides?: CallOverrides): Promise<string>;

    "s_swapAdapter()"(overrides?: CallOverrides): Promise<string>;

    s_userLoanAtIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "s_userLoanAtIndex(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    s_userLoanCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "s_userLoanCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_zQuoter(overrides?: CallOverrides): Promise<string>;

    "s_zQuoter()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    LOAN_REPAYMENT_INTERVAL(overrides?: CallOverrides): Promise<BigNumber>;

    "LOAN_REPAYMENT_INTERVAL()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_COLLATERAL_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_COLLATERAL_AMOUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_SLIPPAGE_BPS(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_SLIPPAGE_BPS()"(overrides?: CallOverrides): Promise<BigNumber>;

    i_AAVE_V3_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    "i_AAVE_V3_POOL()"(overrides?: CallOverrides): Promise<BigNumber>;

    i_BITMOR_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    "i_BITMOR_POOL()"(overrides?: CallOverrides): Promise<BigNumber>;

    i_ORACLE(overrides?: CallOverrides): Promise<BigNumber>;

    "i_ORACLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    s_loanVaultFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "s_loanVaultFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    s_premiumCollector(overrides?: CallOverrides): Promise<BigNumber>;

    "s_premiumCollector()"(overrides?: CallOverrides): Promise<BigNumber>;

    s_swapAdapter(overrides?: CallOverrides): Promise<BigNumber>;

    "s_swapAdapter()"(overrides?: CallOverrides): Promise<BigNumber>;

    s_userLoanAtIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "s_userLoanAtIndex(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_userLoanCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "s_userLoanCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_zQuoter(overrides?: CallOverrides): Promise<BigNumber>;

    "s_zQuoter()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    LOAN_REPAYMENT_INTERVAL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "LOAN_REPAYMENT_INTERVAL()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_COLLATERAL_AMOUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MAX_COLLATERAL_AMOUNT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_SLIPPAGE_BPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MAX_SLIPPAGE_BPS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    i_AAVE_V3_POOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "i_AAVE_V3_POOL()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    i_BITMOR_POOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "i_BITMOR_POOL()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    i_ORACLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "i_ORACLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    s_loanVaultFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "s_loanVaultFactory()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_premiumCollector(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "s_premiumCollector()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_swapAdapter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "s_swapAdapter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    s_userLoanAtIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "s_userLoanAtIndex(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_userLoanCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "s_userLoanCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_zQuoter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "s_zQuoter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
